// Description: This file contains the layout of the application.
// created by: AnotherProject-Team {ColdByDefault}
// Date: 18/12/2024
// CopyRight: All rights reserved
// Version: 3.1.1
// NOT TO BE USED WITHOUT PERMISSION FROM THE AUTHOR (www.coldbydefault.com {ColdByDefault})
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import "./styles/transitions.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "beRich.Library",
  description: "Personal Hub Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        {/* Add a page transition wrapper */}
        <div id="page-content">{children}</div>
      </body>
    </html>
  );
}
